### ISSUE TITLE
Stuff TODO

### ISSUE THREAD

**Issue by YouDirk** [YouDirk/c64-non-sense#1]
* [x] Make: command `x64` to optional dependency
* [x] rename `irq` to `irq_isr` on some places, namespacing
* [x] Double Buffering, check error fractals 
* [x] implement a `Timer` module using `Interrupts`
* [x] Add a debugging option to show the `render_isr` time
* [x] Try out to use C preprocessor `#define` in assembler code to share header files between .c and .S files
* [x] Feature Request to `cc65` for
    - [x] `-Dname` option should pass by default to assembler, without `-Wa` option from `cl65`
    - [x] C Preprocessor support for assembler `ca65`
