### ISSUE TITLE
Stuff todo...

### ISSUE THREAD

**Issue by YouDirk** [YouDirk/c64-non-sense#3]
* [x] Spelling in comment `Graphix.set.charset_exit`
* [x] `void` missing comment how to use `Input.keyboard.petscii.character`
* [x] Bug: Double pressed key, if on `SHIFT+character-key` SHIFT will be released first
* [x] Test if initially set FALSE `Input.keyboard.petscii.changed`
* [x] Add macros `register_uint8(addr_hex, name)`, `register_vector(addr_hex, name, type)` to `define.h`
* [x] Renaming subtitle of C64 NonSense to something like _"The C64 NonSense Game Engine."_
* [x] Change __Year__ of copyright consistent to _"2020 - 2021"_ in all files
* [x] Prepare a Sprite-Module

**Comment by YouDirk** [comment]
Going on with roadmap in #4 ...
